### ISSUE TITLE
Test peeker shows escape characters instead of ANSI colors

### ISSUE THREAD

**Issue by Johnhersh** [vitest-dev/vscode#34]
Tests show ANSI escape characters instead of colors in vscode on Mac.

It doesn't show the actual colors. Instead the output looks like this:
Unable to find an element by: [data-testid="label-text"]

Ignored nodes: comments, <script />, <style />
[36m<body>[39m
  [36m<div>[39m
    [36m<div[39m
      [33mclass[39m=[32m"userIconContainer"[39m
      [33mdata-testid[39m=[32m"label-div"[39m
      [33mstyle[39m=[32m"background-image: url(/src/assets/img/default-avatar.svg);"[39m
    [36m/>[39m
  [36m</div>[39m
[36m</body>[39m

![image](https://user-images.githubusercontent.com/20746719/168831463-c5fecac7-aba4-4e6d-a8a2-cc1b68061b66.png)

 - OS: macOS 12.3.1
 - VSCode version: 1.67.1
 - Vitest version: 0.12.6
- Vitest plugin version: v0.2.2

**Comment by zxch3n** [comment]
Fixed in v0.2.3

**Comment by Tlzps** [comment]
The bug seems to not be totally fixed on 0.2.3

<img width="646" alt="image" src="https://user-images.githubusercontent.com/63225622/170833058-3308293b-2bcf-4328-94aa-ace0328e7255.png">

**Comment by venatiodecorus** [comment]
i'm still seeing this on 0.30.1

![image](https://github.com/vitest-dev/vscode/assets/1077677/57530f43-f94c-4635-9ef2-2f9cc6249e39)
